# Generated by Django 2.2.10 on 2020-07-18 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0023_auto_20200718_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlchecking',
            name='library',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.Library', unique=True),
        ),
        migrations.AlterField(
            model_name='urlcheckingresult',
            name='library',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.Library', unique=True),
        ),
    ]
