# Generated by Django 2.2.10 on 2020-07-19 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0026_auto_20200718_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlchecking',
            name='url',
            field=models.TextField(null=True),
        ),
    ]
